name: CSS Selector Autograding

on:
  push:
    branches:
      - main

jobs:

  grading:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Give Permission
      run: chmod +x grader.sh


    - name: Run Autograder
      run: ./grader.sh
